email: jhw3979@gmail.com
author: maizer2
title: You know maize mean?
description: >-
  AI개발자를 목표로 공부하고있습니다.
  Dongseo University CNSL Lab, ETRI Internship
baseurl: ""
url: "https://maizer2.github.io"
favicon: "/assets/images/favicon.png"
permalink: /:year/:month/:day/:title:output_ext
timezone: Asia/Seoul
lang: "ko"

copyright: "Copyright (c) 2017-{currentYear} <a href='https://github.com/maizer2/' target='_blank'>{author}</a>"

yat:
  date_format: "%b %d, %Y"

markdown: kramdown
kramdown:
  input: GFM

disqus:
  shortname: "maizer2"

paginate: 7

header_pages:
  - pages/index.html
  - pages/categories.html
  - pages/about.md

google_analytics: "G-29TFJFQ4YE"
enableDNT: true

content_width: "1400px"

code_badge:
  enabled: "true"
  color: "#fff"
  background_color: "#ff4e00"
  text_transform: "uppercase"

collections:
  posts:
    output: true

theme_color: snowwhite
brand_color: orangered
night_mode: "on"
debug: false
header_transparent: true

port: 4000
future: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-spaceship

exclude:
  - README.md
  - _posts_temporary
