title: You know maize mean?
email: jhw3979@gmail.com
author: maizer2
copyright: "Copyright © 2021-{currentYear} <a href='https://github.com/vanhiupun/' target='_blank'>{author}</a>""
description: >- # this means to ignore newlines until "baseurl:"
  AI개발자를 목표로 공부하고있습니다.
  Dongseo Unversity CNSL Lab, ETRI Internship
baseurl: ""
url: "https://maizer2.github.io/"
favicon: "/assets/images/favicon/favicon-96x96.png"

yat:
  date_format: "%b %d, %Y"

# If you want more debug log, you can set true
debug: true

# If you don't want transparent header, you can set false
header_transparent: true

# Google analytics
google_analytics: "G-QNKWVZVJH2"

# If you want to generate website sitemap, you can set true
sitemap: true

# If you want to change site language, you can set lang option
# lang: "ko"  # default lang is en

# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
translate_langs: []
#  - lang: en
#   img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
#    text: English
#
#  - lang: fr
#    img: https://cdn.countryflags.com/thumbs/france/flag-400.png
#    text: French
#
#  - lang: zh-CN
#    img: https://cdn.countryflags.com/thumbs/china/flag-400.png
#    text: Chinese(Simple)
#
#   - lang: ja
#    img: https://cdn.countryflags.com/thumbs/japan/flag-400.png
#    text: Japanese
#
#  - lang: ko
#    img: https://cdn.countryflags.com/thumbs/south-korea/flag-400.png
#    text: Korean
#
#  - lang: ru
#    img: https://cdn.countryflags.com/thumbs/russia/flag-400.png
#    text: Russian

# You can choose a theme color
# Default theme colors as below:
#coolblack: #090a0b
#spacegrey: #353535
#snowwhite: #ffffff

theme_color: snowwhite

# Custom color as below:
# theme_color: "#882250"

# You can choose a brand color
# Default brand colors as below:
# orangered: #ff5100
# greatgold: #f2cb05
# greenblue: #389092
#
# brand_color: orangered
#
# Custom color as below:
# brand_color: "#1a8e42"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is"manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
#
night_mode: "on"

# Code badge setting
# You can enable or disable the code badge and so on
# code_badge:
#   enabled: "true"
#   color: "#fff"
#   background_color: "#ff4e00"
#   text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - index.html
#   - archives.html
#   - categories.html
#   - tags.html
#   - about.md

# Page default value
defaults:
  home:
    heading: "maizer's blog"
    subheading: "CNSL_lab, ETRI Internship"
    banner: "/assets/images/my_img/img.jpg"

# Banner default settings
# These banner settings are for global banner default, but you can also
# config it by the front matter for one specific post
# banner:
#   video: null             # Video banner source
#   loop: true              # Video loop
#   volume: 0               # Video volume (100% is 1.0)
#   start_at: 0             # Video start time
#   image: null             # Image banner source
#   opacity: 1.0            # Banner opacity (100% is 1.0)
#   background: "rgba(0, 0, 0, 0.8)"  # Banner background (Could be a image)
#   height: "640px"         # Banner default height
#   min_height: null        # Banner minium height
#   heading_style: null     # Custom heading style (e.g. "font-weight: bold; text-decoration: underline")
#   subheading_style: null  # Custom subheading style (e.g. color: gold)

# Excerpt size setting
excerpt_size: 250

# Pagination setting
paginate: 7

# Disqus comments
disqus:
   shortname: "maizer2"

#gitment:
#  username: "" # 
#  repo: "" # 
#  client_id: "" # 
#  client_secret: "" # 
#  redirect_uri: "" # 

# Build settings
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
